// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEveXcogA9WLeD38kteeGX1Y4Xv2y8_so',
    appId: '1:474918918569:web:00b8abe6f3cafa9bb1ccb8',
    messagingSenderId: '474918918569',
    projectId: 'cartkaro-404b6',
    authDomain: 'cartkaro-404b6.firebaseapp.com',
    storageBucket: 'cartkaro-404b6.firebasestorage.app',
    measurementId: 'G-R59RZFMR12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPvPS3_DXFrCsDGI0yx4YxLu2qzSpQ7wI',
    appId: '1:474918918569:android:fadbe9ada64e2969b1ccb8',
    messagingSenderId: '474918918569',
    projectId: 'cartkaro-404b6',
    storageBucket: 'cartkaro-404b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnwx95imsoQJ5eIdv46KnZ7ZuCohItXf0',
    appId: '1:474918918569:ios:9e14fbf14ac2fef8b1ccb8',
    messagingSenderId: '474918918569',
    projectId: 'cartkaro-404b6',
    storageBucket: 'cartkaro-404b6.firebasestorage.app',
    iosBundleId: 'com.example.cartkaroPartnerHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnwx95imsoQJ5eIdv46KnZ7ZuCohItXf0',
    appId: '1:474918918569:ios:9e14fbf14ac2fef8b1ccb8',
    messagingSenderId: '474918918569',
    projectId: 'cartkaro-404b6',
    storageBucket: 'cartkaro-404b6.firebasestorage.app',
    iosBundleId: 'com.example.cartkaroPartnerHub',
  );
}
